import type { NextPage } from 'next'
import Head from 'next/head'
import Card from '../components/Card/card'
interface props {
  name: string
}
const Home: NextPage<props> = ({ name }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container'>
        <Card label='Heading card' />
      </main>
    </div>
  )
}

export const getServerSideProps = () => {
  return {
    props: {
      name: "test"
    }
  }
}

export default Home
